# Generated by Django 4.2.14 on 2024-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
        migrations.DeleteModel(
            name='FeedBackStudent',
        ),
    ]
