# Generated by Django 4.2.14 on 2024-07-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cars_owners_remove_staffs_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='admin',
        ),
        migrations.AddField(
            model_name='owners',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='owners',
            name='first_name',
            field=models.CharField(default='john', max_length=20),
        ),
        migrations.AddField(
            model_name='owners',
            name='last_name',
            field=models.CharField(default='doe', max_length=20),
        ),
        migrations.AddField(
            model_name='owners',
            name='owner_picture',
            field=models.FileField(default='picture.jpg', upload_to='media/'),
        ),
    ]
