# Generated by Django 4.2.14 on 2024-07-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_owners_admin_owners_email_owners_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='car',
        ),
    ]
