# Generated by Django 4.2.14 on 2024-07-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_owners_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.owners'),
        ),
    ]
